# CPI Analysis

In [1]:
import numpy as np

arr = np.arange(9).reshape(3,3)

print(arr[:, :])
print(arr[:, [1,0,2]])



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [2]:
# import the necessary libraries and define utility functions
import pandas as pd


def overview(df):
    print(df.head(5))
    print(df.columns)
    print(df.describe())

In [3]:
# import CPI data from 2012-2021
CPI_2021 = pd.read_csv("datasets/CPI/CPI2021-Table 1.csv", header=2)
CPI_2020 = pd.read_csv("datasets/CPI/CPI2020-Table 1.csv", header=2)
CPI_2019 = pd.read_csv("datasets/CPI/CPI2019-Table 1.csv", header=2)
CPI_2018 = pd.read_csv("datasets/CPI/CPI2018-Table 1.csv", header=2)
CPI_2017 = pd.read_csv("datasets/CPI/CPI2017-Table 1.csv", header=2)
CPI_2016 = pd.read_csv("datasets/CPI/CPI2016-Table 1.csv")
CPI_2015 = pd.read_csv("datasets/CPI/CPI2015-Table 1.csv")
CPI_2014 = pd.read_csv("datasets/CPI/CPI2014-Table 1.csv")
CPI_2013 = pd.read_csv("datasets/CPI/CPI2013-Table 1.csv", header=1)
CPI_2012 = pd.read_csv("datasets/CPI/CPI2012-Table 1.csv")

# retrieve the Country, ISO3, Region, CPI score, and rank columns
# 2021

CPI_2021 = CPI_2021.iloc[:, :5]
CPI_2021.rename(columns={ "Country / Territory": "Country", "Rank": "Rank 2021"}, inplace=True)

# 2020
CPI_2020 = CPI_2020.iloc[:, :5]
CPI_2020.rename(columns={ "Rank": "Rank 2020"}, inplace=True)

CPI = CPI_2021.merge(CPI_2020, how="outer", on=["Country", "ISO3", "Region"])

# 2019
CPI_2019 = CPI_2019.iloc[:, :5]
CPI_2019.rename(columns={ "Rank": "Rank 2019"}, inplace=True)

CPI = CPI.merge(CPI_2019, how="outer", on=["Country", "ISO3", "Region"])

# 2018
CPI_2018 = CPI_2018.iloc[:, :5]
CPI_2018.rename(columns={ "Rank ": "Rank 2018"}, inplace=True)

CPI = CPI.merge(CPI_2018, how="outer", on=["Country", "ISO3", "Region"])


# 2017
CPI_2017 = CPI_2017.iloc[:, :5]
CPI_2017.rename(columns={ "Rank ": "Rank 2017"}, inplace=True)

CPI = CPI.merge(CPI_2017, how="outer", on=["Country", "ISO3", "Region"])

# 2016
CPI_2016 = CPI_2016.iloc[:, :4]
CPI_2016.rename(columns={ "CPI2016": "CPI score 2016", "Rank": "Rank 2016"}, inplace=True)

CPI = CPI.merge(CPI_2016, how="outer", on=["Country", "Region"])

# 2015
CPI_2015 = CPI_2015.iloc[:, :5]
CPI_2015.drop("Region", axis=1, inplace=True)
CPI_2015.rename(columns={ "CPI 2015 Score": "CPI score 2015", "Country Rank": "Rank 2015", "Country/Territory": "Country", "Country Code": "ISO3"}, inplace=True)

CPI = CPI.merge(CPI_2015, how="outer", on=["Country", "ISO3"])

# 2014
CPI_2014 = CPI_2014.iloc[:, :5]
CPI_2014.drop("Region", axis=1, inplace=True)
CPI_2014.rename(columns={ "CPI 2014": "CPI score 2014", "Country Rank": "Rank 2014", "Country/Territory": "Country", "Country Code": "ISO3"}, inplace=True)
CPI = CPI.merge(CPI_2014, how="outer", on=["Country", "ISO3"], suffixes=["", "_2014"])

# 2013
CPI_2013 = CPI_2013.iloc[:, :7]
CPI_2013.drop(labels=["Region", "IFS Code", "Country Rank.1"], axis=1, inplace=True)
CPI_2013.rename(columns={ "CPI 2013 Score": "CPI score 2013", "Country Rank": "Rank 2013", "Country / Territory": "Country", "Country Code": "ISO3", "WB Code": "ISO3"}, inplace=True)
CPI = CPI.merge(CPI_2013, how="outer", on=["Country", "ISO3"])

# 2012
CPI_2012 = CPI_2012.iloc[:, :4]
CPI_2012.drop(labels=["Unnamed: 2"], axis=1, inplace=True)
CPI_2012.rename(columns={ "CPI 2012 Score": "CPI score 2012", "Country Rank": "Rank 2012", "Country / Territory": "Country"}, inplace=True)
CPI = CPI.merge(CPI_2012, how="outer", on=["Country"])


# sanity check
CPI

Country ISO3 Region  CPI score 2021  Rank 2021  CPI score 2020  \
0           Denmark  DNK  WE/EU            88.0        1.0            88.0   
1           Finland  FIN  WE/EU            88.0        1.0            85.0   
2       New Zealand  NZL     AP            88.0        1.0            88.0   
3            Norway  NOR  WE/EU            85.0        4.0            84.0   
4         Singapore  SGP     AP            85.0        4.0            85.0   
..              ...  ...    ...             ...        ...             ...   
209   Korea (North)  PRK    NaN             NaN        NaN             NaN   
210   United States  USA    NaN             NaN        NaN             NaN   
211   Côte d´Ivoire  CIV    NaN             NaN        NaN             NaN   
212  Congo Republic  COG    NaN             NaN        NaN             NaN   
213     Puerto Rico  PRI    NaN             NaN        NaN             NaN   

     Rank 2020  CPI score 2019  Rank 2019  CPI Score 2018  ...  \
0          1.0            87.0        1.0            88.0  ...   
1          3.0            86.0        3.0            85.0  ...   
2          1.0            87.0        1.0            87.0  ...   
3          7.0            84.0        7.0            84.0  ...   
4          3.0            85.0        4.0            85.0  ...   
..         ...             ...        ...             ...  ...   
209        NaN             NaN        NaN             NaN  ...   
210        NaN             NaN        NaN             NaN  ...   
211        NaN             NaN        NaN             NaN  ...   
212        NaN             NaN        NaN             NaN  ...   
213        NaN             NaN        NaN             NaN  ...   

     CPI score 2016  Rank 2016  Rank 2015  CPI score 2015  Rank 2014  \
0              90.0        1.0        1.0            91.0        1.0   
1              89.0        3.0        3.0            90.0        3.0   
2              90.0        1.0        1.0            91.0        2.0   
3              85.0        6.0        5.0            88.0        5.0   
4              84.0        7.0        7.0            85.0        7.0   
..              ...        ...        ...             ...        ...   
209             NaN        NaN      167.0             8.0      174.0   
210             NaN        NaN       16.0            76.0       17.0   
211             NaN        NaN      106.0            32.0      115.0   
212             NaN        NaN      146.0            23.0      152.0   
213             NaN        NaN        NaN             NaN       31.0   

     CPI score 2014  Rank 2013  CPI score 2013  Rank 2012  CPI score 2012  
0              92.0        1.0            91.0        1.0            90.0  
1              89.0        3.0            89.0        1.0            90.0  
2              91.0        1.0            91.0        1.0            90.0  
3              86.0        5.0            86.0        7.0            85.0  
4              84.0        5.0            86.0        5.0            87.0  
..              ...        ...             ...        ...             ...  
209             8.0      175.0             8.0      174.0             8.0  
210            74.0       19.0            73.0       19.0            73.0  
211            32.0      136.0            27.0      130.0            29.0  
212            23.0      154.0            22.0      144.0            26.0  
213            63.0       33.0            62.0       33.0            63.0  

[214 rows x 23 columns]

In [4]:
CPI.head(5)

Country ISO3 Region  CPI score 2021  Rank 2021  CPI score 2020  \
0      Denmark  DNK  WE/EU            88.0        1.0            88.0   
1      Finland  FIN  WE/EU            88.0        1.0            85.0   
2  New Zealand  NZL     AP            88.0        1.0            88.0   
3       Norway  NOR  WE/EU            85.0        4.0            84.0   
4    Singapore  SGP     AP            85.0        4.0            85.0   

   Rank 2020  CPI score 2019  Rank 2019  CPI Score 2018  ...  CPI score 2016  \
0        1.0            87.0        1.0            88.0  ...            90.0   
1        3.0            86.0        3.0            85.0  ...            89.0   
2        1.0            87.0        1.0            87.0  ...            90.0   
3        7.0            84.0        7.0            84.0  ...            85.0   
4        3.0            85.0        4.0            85.0  ...            84.0   

   Rank 2016  Rank 2015  CPI score 2015  Rank 2014  CPI score 2014  Rank 2013  \
0        1.0        1.0            91.0        1.0            92.0        1.0   
1        3.0        3.0            90.0        3.0            89.0        3.0   
2        1.0        1.0            91.0        2.0            91.0        1.0   
3        6.0        5.0            88.0        5.0            86.0        5.0   
4        7.0        7.0            85.0        7.0            84.0        5.0   

   CPI score 2013  Rank 2012  CPI score 2012  
0            91.0        1.0            90.0  
1            89.0        1.0            90.0  
2            91.0        1.0            90.0  
3            86.0        7.0            85.0  
4            86.0        5.0            87.0  

[5 rows x 23 columns]

In [5]:
CPI.columns

Index(['Country', 'ISO3', 'Region', 'CPI score 2021', 'Rank 2021',
       'CPI score 2020', 'Rank 2020', 'CPI score 2019', 'Rank 2019',
       'CPI Score 2018', 'Rank 2018', 'CPI Score 2017', 'Rank 2017',
       'CPI score 2016', 'Rank 2016', 'Rank 2015', 'CPI score 2015',
       'Rank 2014', 'CPI score 2014', 'Rank 2013', 'CPI score 2013',
       'Rank 2012', 'CPI score 2012'],
      dtype='object')

In [6]:
CPI.describe()

CPI score 2021   Rank 2021  CPI score 2020   Rank 2020  CPI score 2019  \
count      180.000000  180.000000      180.000000  180.000000      180.000000   
mean        43.266667   89.072222       43.344444   88.966667       43.166667   
std         18.780591   51.881798       18.875162   51.759532       18.960264   
min         11.000000    1.000000       12.000000    1.000000        9.000000   
25%         29.750000   45.000000       29.000000   45.000000       29.000000   
50%         39.000000   87.000000       40.000000   86.000000       39.500000   
75%         55.000000  130.000000       56.000000  134.000000       56.000000   
max         88.000000  180.000000       88.000000  179.000000       87.000000   

        Rank 2019  CPI Score 2018   Rank 2018  CPI Score 2017   Rank 2017  \
count  180.000000      180.000000  180.000000      181.000000  180.000000   
mean    88.966667       43.116667   89.127778       43.072210   89.116667   
std     51.656353       19.142008   51.748320       18.998547   51.765185   
min      1.000000       10.000000    1.000000        9.000000    1.000000   
25%     44.000000       29.000000   45.000000       29.000000   45.000000   
50%     88.000000       38.000000   89.000000       39.000000   88.000000   
75%    130.000000       57.000000  132.000000       56.000000  135.000000   
max    180.000000       88.000000  180.000000       89.000000  180.000000   

       CPI score 2016   Rank 2016   Rank 2015  CPI score 2015   Rank 2014  \
count      176.000000  176.000000  168.000000      168.000000  175.000000   
mean        42.948864   87.198864   83.160714       42.595238   86.571429   
std         19.436716   50.543562   48.265152       20.195819   50.400058   
min         10.000000    1.000000    1.000000        8.000000    1.000000   
25%         29.000000   44.000000   42.250000       28.000000   44.000000   
50%         38.000000   87.000000   83.000000       37.000000   85.000000   
75%         57.000000  131.000000  123.000000       54.250000  126.000000   
max         90.000000  176.000000  167.000000       91.000000  174.000000   

       CPI score 2014   Rank 2013  CPI score 2013   Rank 2012  CPI score 2012  
count      175.000000  177.000000      177.000000  185.000000      185.000000  
mean        43.268571   87.644068       42.655367   87.145946       43.118919  
std         19.840510   50.863597       19.922859   50.263926       19.504930  
min          8.000000    1.000000        8.000000    1.000000        8.000000  
25%         29.000000   45.000000       28.000000   45.000000       29.000000  
50%         38.000000   83.000000       38.000000   83.000000       38.000000  
75%         55.000000  127.000000       56.000000  130.000000       56.000000  
max         92.000000  175.000000       91.000000  174.000000       90.000000

In [7]:
CPI.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 214 entries, 0 to 213
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country         213 non-null    object 
 1   ISO3            200 non-null    object 
 2   Region          197 non-null    object 
 3   CPI score 2021  180 non-null    float64
 4   Rank 2021       180 non-null    float64
 5   CPI score 2020  180 non-null    float64
 6   Rank 2020       180 non-null    float64
 7   CPI score 2019  180 non-null    float64
 8   Rank 2019       180 non-null    float64
 9   CPI Score 2018  180 non-null    float64
 10  Rank 2018       180 non-null    float64
 11  CPI Score 2017  181 non-null    float64
 12  Rank 2017       180 non-null    float64
 13  CPI score 2016  176 non-null    float64
 14  Rank 2016       176 non-null    float64
 15  Rank 2015       168 non-null    float64
 16  CPI score 2015  168 non-null    float64
 17  Rank 2014       175 non-null    flo