# CPI Analysis

In [1]:
import numpy as np

arr = np.arange(9).reshape(3,3)

print(arr[:, :])
print(arr[:, [1,0,2]])



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [2]:
# import the necessary libraries and define utility functions
import pandas as pd
import numpy as np


def overview(df):
    print(df.head(5))
    print(df.columns)
    print(df.describe())

In [3]:
# import CPI data from 2012-2021
CPI_2021 = pd.read_csv("datasets/CPI/CPI2021-Table 1.csv", header=2)
CPI_2020 = pd.read_csv("datasets/CPI/CPI2020-Table 1.csv", header=2)
CPI_2019 = pd.read_csv("datasets/CPI/CPI2019-Table 1.csv", header=2)
CPI_2018 = pd.read_csv("datasets/CPI/CPI2018-Table 1.csv", header=2)
CPI_2017 = pd.read_csv("datasets/CPI/CPI2017-Table 1.csv", header=2)
CPI_2016 = pd.read_csv("datasets/CPI/CPI2016-Table 1.csv")
CPI_2015 = pd.read_csv("datasets/CPI/CPI2015-Table 1.csv")
CPI_2014 = pd.read_csv("datasets/CPI/CPI2014-Table 1.csv")
CPI_2013 = pd.read_csv("datasets/CPI/CPI2013-Table 1.csv", header=1)
CPI_2012 = pd.read_csv("datasets/CPI/CPI2012-Table 1.csv")

# retrieve the Country, ISO3, Region, CPI score, and rank columns
# 2021

CPI_2021 = CPI_2021.iloc[:, :5]
CPI_2021.rename(columns={ "Country / Territory": "Country", "Rank": "Rank 2021"}, inplace=True)

# 2020
CPI_2020 = CPI_2020.iloc[:, :5]
CPI_2020.rename(columns={ "Rank": "Rank 2020"}, inplace=True)

CPI = CPI_2021.merge(CPI_2020, how="outer", on=["Country", "ISO3", "Region"])

# 2019
CPI_2019 = CPI_2019.iloc[:, :5]
CPI_2019.rename(columns={ "Rank": "Rank 2019"}, inplace=True)

CPI = CPI.merge(CPI_2019, how="outer", on=["Country", "ISO3", "Region"])

# 2018
CPI_2018 = CPI_2018.iloc[:, :5]
CPI_2018.rename(columns={ "Rank ": "Rank 2018", "CPI Score 2018": "CPI score 2018"}, inplace=True)

CPI = CPI.merge(CPI_2018, how="outer", on=["Country", "ISO3", "Region"])


# 2017
CPI_2017 = CPI_2017.iloc[:, :5]
CPI_2017.rename(columns={ "Rank ": "Rank 2017"}, inplace=True)

CPI = CPI.merge(CPI_2017, how="outer", on=["Country", "ISO3", "Region"])

# 2016
CPI_2016 = CPI_2016.iloc[:, :4]
CPI_2016.rename(columns={ "CPI2016": "CPI score 2016", "Rank": "Rank 2016"}, inplace=True)

CPI = CPI.merge(CPI_2016, how="outer", on=["Country"], suffixes=["", "_2016"])

# 2015
CPI_2015 = CPI_2015.iloc[:, :5]
CPI_2015.drop("Region", axis=1, inplace=True)
CPI_2015.rename(columns={ "CPI 2015 Score": "CPI score 2015", "Country Rank": "Rank 2015", "Country/Territory": "Country", "Country Code": "ISO3"}, inplace=True)

CPI = CPI.merge(CPI_2015, how="outer", on=["Country"], suffixes=["", "_2015"])

# 2014
CPI_2014 = CPI_2014.iloc[:, :5]
CPI_2014.drop("Region", axis=1, inplace=True)
CPI_2014.rename(columns={ "CPI 2014": "CPI score 2014", "Country Rank": "Rank 2014", "Country/Territory": "Country", "Country Code": "ISO3"}, inplace=True)
CPI = CPI.merge(CPI_2014, how="outer", on=["Country"], suffixes=["", "_2014"])

# 2013
CPI_2013 = CPI_2013.iloc[:, :7]
CPI_2013.drop(labels=["Region", "IFS Code", "Country Rank.1"], axis=1, inplace=True)
CPI_2013.rename(columns={ "CPI 2013 Score": "CPI score 2013", "Country Rank": "Rank 2013", "Country / Territory": "Country", "Country Code": "ISO3", "WB Code": "ISO3"}, inplace=True)
CPI = CPI.merge(CPI_2013, how="outer", on=["Country"], suffixes=["", "_2013"])

# 2012
CPI_2012 = CPI_2012.iloc[:, :4]
CPI_2012.drop(labels=["Unnamed: 2"], axis=1, inplace=True)
CPI_2012.rename(columns={ "CPI 2012 Score": "CPI score 2012", "Country Rank": "Rank 2012", "Country / Territory": "Country"}, inplace=True)
CPI = CPI.merge(CPI_2012, how="outer", on=["Country"], suffixes=["", "_2012"])


# sanity check
CPI

Country ISO3 Region  CPI score 2021  Rank 2021  CPI score 2020  \
0           Denmark  DNK  WE/EU            88.0        1.0            88.0   
1           Finland  FIN  WE/EU            88.0        1.0            85.0   
2       New Zealand  NZL     AP            88.0        1.0            88.0   
3            Norway  NOR  WE/EU            85.0        4.0            84.0   
4         Singapore  SGP     AP            85.0        4.0            85.0   
..              ...  ...    ...             ...        ...             ...   
198   Korea (North)  NaN    NaN             NaN        NaN             NaN   
199   United States  NaN    NaN             NaN        NaN             NaN   
200   Côte d´Ivoire  NaN    NaN             NaN        NaN             NaN   
201  Congo Republic  NaN    NaN             NaN        NaN             NaN   
202     Puerto Rico  NaN    NaN             NaN        NaN             NaN   

     Rank 2020  CPI score 2019  Rank 2019  CPI score 2018  ...  ISO3_2015  \
0          1.0            87.0        1.0            88.0  ...        DNK   
1          3.0            86.0        3.0            85.0  ...        FIN   
2          1.0            87.0        1.0            87.0  ...        NZL   
3          7.0            84.0        7.0            84.0  ...        NOR   
4          3.0            85.0        4.0            85.0  ...        SGP   
..         ...             ...        ...             ...  ...        ...   
198        NaN             NaN        NaN             NaN  ...        PRK   
199        NaN             NaN        NaN             NaN  ...        USA   
200        NaN             NaN        NaN             NaN  ...        CIV   
201        NaN             NaN        NaN             NaN  ...        COG   
202        NaN             NaN        NaN             NaN  ...        NaN   

     CPI score 2015  Rank 2014  ISO3_2014  CPI score 2014 Rank 2013  \
0              91.0        1.0        DNK            92.0       1.0   
1              90.0        3.0        FIN            89.0       3.0   
2              91.0        2.0        NZL            91.0       1.0   
3              88.0        5.0        NOR            86.0       5.0   
4              85.0        7.0        SGP            84.0       5.0   
..              ...        ...        ...             ...       ...   
198             8.0      174.0        PRK             8.0     175.0   
199            76.0       17.0        USA            74.0      19.0   
200            32.0      115.0        CIV            32.0     136.0   
201            23.0      152.0        COG            23.0     154.0   
202             NaN       31.0        PRI            63.0      33.0   

     ISO3_2013 CPI score 2013  Rank 2012  CPI score 2012  
0          DNK           91.0        1.0            90.0  
1          FIN           89.0        1.0            90.0  
2          NZL           91.0        1.0            90.0  
3          NOR           86.0        7.0            85.0  
4          SGP           86.0        5.0            87.0  
..         ...            ...        ...             ...  
198        PRK            8.0      174.0             8.0  
199        USA           73.0       19.0            73.0  
200        CIV           27.0      130.0            29.0  
201        COG           22.0      144.0            26.0  
202        PRI           62.0       33.0            63.0  

[203 rows x 27 columns]

In [4]:
CPI.head(5)

Country ISO3 Region  CPI score 2021  Rank 2021  CPI score 2020  \
0      Denmark  DNK  WE/EU            88.0        1.0            88.0   
1      Finland  FIN  WE/EU            88.0        1.0            85.0   
2  New Zealand  NZL     AP            88.0        1.0            88.0   
3       Norway  NOR  WE/EU            85.0        4.0            84.0   
4    Singapore  SGP     AP            85.0        4.0            85.0   

   Rank 2020  CPI score 2019  Rank 2019  CPI score 2018  ...  ISO3_2015  \
0        1.0            87.0        1.0            88.0  ...        DNK   
1        3.0            86.0        3.0            85.0  ...        FIN   
2        1.0            87.0        1.0            87.0  ...        NZL   
3        7.0            84.0        7.0            84.0  ...        NOR   
4        3.0            85.0        4.0            85.0  ...        SGP   

   CPI score 2015  Rank 2014  ISO3_2014  CPI score 2014 Rank 2013  ISO3_2013  \
0            91.0        1.0        DNK            92.0       1.0        DNK   
1            90.0        3.0        FIN            89.0       3.0        FIN   
2            91.0        2.0        NZL            91.0       1.0        NZL   
3            88.0        5.0        NOR            86.0       5.0        NOR   
4            85.0        7.0        SGP            84.0       5.0        SGP   

  CPI score 2013  Rank 2012  CPI score 2012  
0           91.0        1.0            90.0  
1           89.0        1.0            90.0  
2           91.0        1.0            90.0  
3           86.0        7.0            85.0  
4           86.0        5.0            87.0  

[5 rows x 27 columns]

In [5]:
CPI.tail(5)

Country ISO3 Region  CPI score 2021  Rank 2021  CPI score 2020  \
198   Korea (North)  NaN    NaN             NaN        NaN             NaN   
199   United States  NaN    NaN             NaN        NaN             NaN   
200   Côte d´Ivoire  NaN    NaN             NaN        NaN             NaN   
201  Congo Republic  NaN    NaN             NaN        NaN             NaN   
202     Puerto Rico  NaN    NaN             NaN        NaN             NaN   

     Rank 2020  CPI score 2019  Rank 2019  CPI score 2018  ...  ISO3_2015  \
198        NaN             NaN        NaN             NaN  ...        PRK   
199        NaN             NaN        NaN             NaN  ...        USA   
200        NaN             NaN        NaN             NaN  ...        CIV   
201        NaN             NaN        NaN             NaN  ...        COG   
202        NaN             NaN        NaN             NaN  ...        NaN   

     CPI score 2015  Rank 2014  ISO3_2014  CPI score 2014 Rank 2013  \
198             8.0      174.0        PRK             8.0     175.0   
199            76.0       17.0        USA            74.0      19.0   
200            32.0      115.0        CIV            32.0     136.0   
201            23.0      152.0        COG            23.0     154.0   
202             NaN       31.0        PRI            63.0      33.0   

     ISO3_2013 CPI score 2013  Rank 2012  CPI score 2012  
198        PRK            8.0      174.0             8.0  
199        USA           73.0       19.0            73.0  
200        CIV           27.0      130.0            29.0  
201        COG           22.0      144.0            26.0  
202        PRI           62.0       33.0            63.0  

[5 rows x 27 columns]

In [6]:
CPI.columns

Index(['Country', 'ISO3', 'Region', 'CPI score 2021', 'Rank 2021',
       'CPI score 2020', 'Rank 2020', 'CPI score 2019', 'Rank 2019',
       'CPI score 2018', 'Rank 2018', 'CPI Score 2017', 'Rank 2017',
       'CPI score 2016', 'Rank 2016', 'Region_2016', 'Rank 2015', 'ISO3_2015',
       'CPI score 2015', 'Rank 2014', 'ISO3_2014', 'CPI score 2014',
       'Rank 2013', 'ISO3_2013', 'CPI score 2013', 'Rank 2012',
       'CPI score 2012'],
      dtype='object')

In [7]:
CPI.describe()

CPI score 2021   Rank 2021  CPI score 2020   Rank 2020  CPI score 2019  \
count      180.000000  180.000000      180.000000  180.000000      180.000000   
mean        43.266667   89.072222       43.344444   88.966667       43.166667   
std         18.780591   51.881798       18.875162   51.759532       18.960264   
min         11.000000    1.000000       12.000000    1.000000        9.000000   
25%         29.750000   45.000000       29.000000   45.000000       29.000000   
50%         39.000000   87.000000       40.000000   86.000000       39.500000   
75%         55.000000  130.000000       56.000000  134.000000       56.000000   
max         88.000000  180.000000       88.000000  179.000000       87.000000   

        Rank 2019  CPI score 2018   Rank 2018  CPI Score 2017   Rank 2017  \
count  180.000000      180.000000  180.000000      181.000000  180.000000   
mean    88.966667       43.116667   89.127778       43.072210   89.116667   
std     51.656353       19.142008   51.748320       18.998547   51.765185   
min      1.000000       10.000000    1.000000        9.000000    1.000000   
25%     44.000000       29.000000   45.000000       29.000000   45.000000   
50%     88.000000       38.000000   89.000000       39.000000   88.000000   
75%    130.000000       57.000000  132.000000       56.000000  135.000000   
max    180.000000       88.000000  180.000000       89.000000  180.000000   

       CPI score 2016   Rank 2016   Rank 2015  CPI score 2015   Rank 2014  \
count      176.000000  176.000000  168.000000      168.000000  175.000000   
mean        42.948864   87.198864   83.160714       42.595238   86.571429   
std         19.436716   50.543562   48.265152       20.195819   50.400058   
min         10.000000    1.000000    1.000000        8.000000    1.000000   
25%         29.000000   44.000000   42.250000       28.000000   44.000000   
50%         38.000000   87.000000   83.000000       37.000000   85.000000   
75%         57.000000  131.000000  123.000000       54.250000  126.000000   
max         90.000000  176.000000  167.000000       91.000000  174.000000   

       CPI score 2014   Rank 2013  CPI score 2013   Rank 2012  CPI score 2012  
count      175.000000  177.000000      177.000000  176.000000      176.000000  
mean        43.268571   87.644068       42.655367   87.170455       43.267045  
std         19.840510   50.863597       19.922859   50.518618       19.674269  
min          8.000000    1.000000        8.000000    1.000000        8.000000  
25%         29.000000   45.000000       28.000000   44.500000       28.750000  
50%         38.000000   83.000000       38.000000   88.000000       37.000000  
75%         55.000000  127.000000       56.000000  130.750000       56.250000  
max         92.000000  175.000000       91.000000  174.000000       90.000000

In [8]:
CPI.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 203 entries, 0 to 202
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country         202 non-null    object 
 1   ISO3            186 non-null    object 
 2   Region          186 non-null    object 
 3   CPI score 2021  180 non-null    float64
 4   Rank 2021       180 non-null    float64
 5   CPI score 2020  180 non-null    float64
 6   Rank 2020       180 non-null    float64
 7   CPI score 2019  180 non-null    float64
 8   Rank 2019       180 non-null    float64
 9   CPI score 2018  180 non-null    float64
 10  Rank 2018       180 non-null    float64
 11  CPI Score 2017  181 non-null    float64
 12  Rank 2017       180 non-null    float64
 13  CPI score 2016  176 non-null    float64
 14  Rank 2016       176 non-null    float64
 15  Region_2016     176 non-null    object 
 16  Rank 2015       168 non-null    float64
 17  ISO3_2015       168 non-null    obj

In [9]:
# there are some null values in the final dataframe
# let's see if we can clean them up

# Country's frequency table

CPI["Country"].value_counts(dropna=False)

Denmark               1
Mauritania            1
Djibouti              1
Dominican Republic    1
Laos                  1
                     ..
South Africa          1
Tunisia               1
Ghana                 1
Hungary               1
Puerto Rico           1
Name: Country, Length: 203, dtype: int64

In [10]:
# Country's columns
CPI.columns

Index(['Country', 'ISO3', 'Region', 'CPI score 2021', 'Rank 2021',
       'CPI score 2020', 'Rank 2020', 'CPI score 2019', 'Rank 2019',
       'CPI score 2018', 'Rank 2018', 'CPI Score 2017', 'Rank 2017',
       'CPI score 2016', 'Rank 2016', 'Region_2016', 'Rank 2015', 'ISO3_2015',
       'CPI score 2015', 'Rank 2014', 'ISO3_2014', 'CPI score 2014',
       'Rank 2013', 'ISO3_2013', 'CPI score 2013', 'Rank 2012',
       'CPI score 2012'],
      dtype='object')

In [11]:
# we discovered some duplicate ISO3 columns

# the ISO3 code for certain countries has changed some time in between 2012 to 2021
# e.g. Montenegro's ISO3 was once MON but it changed to MNE after the CPI 2015 data was published
# trivia: actually, the ISO3 change for Montenegro happened in 2007, but the CPI dataset still used the old ISO3 code

# we'll keep the newest ISO3 and drop the rest
CPI = CPI.drop(["ISO3_2015", "ISO3_2014", "ISO3_2013"], axis=1)
CPI.columns
# CPI[CPI["ISO3"] == np.nan]

Index(['Country', 'ISO3', 'Region', 'CPI score 2021', 'Rank 2021',
       'CPI score 2020', 'Rank 2020', 'CPI score 2019', 'Rank 2019',
       'CPI score 2018', 'Rank 2018', 'CPI Score 2017', 'Rank 2017',
       'CPI score 2016', 'Rank 2016', 'Region_2016', 'Rank 2015',
       'CPI score 2015', 'Rank 2014', 'CPI score 2014', 'Rank 2013',
       'CPI score 2013', 'Rank 2012', 'CPI score 2012'],
      dtype='object')

In [12]:
# there's a null value we haven't checked
# the curious thing is the value_counts doesn't show the NaN value
CPI["Country"].value_counts(dropna=False)

# we'll directly retrieve it with isnull
CPI[CPI["Country"].isnull()]



Country ISO3 Region  CPI score 2021  Rank 2021  CPI score 2020  Rank 2020  \
186     NaN  NaN    NaN             NaN        NaN             NaN        NaN   

     CPI score 2019  Rank 2019  CPI score 2018  ...  Rank 2016  Region_2016  \
186             NaN        NaN             NaN  ...        NaN          NaN   

     Rank 2015  CPI score 2015  Rank 2014 CPI score 2014  Rank 2013  \
186        NaN             NaN        NaN            NaN        NaN   

     CPI score 2013  Rank 2012  CPI score 2012  
186             NaN        NaN             NaN  

[1 rows x 24 columns]

In [13]:
# row with index 186 has NaN for all its columns
# it probably came from an empty row in one of the original datasets
# we can safely drop it
CPI.drop(186, axis=0, inplace=True)
CPI.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 202 entries, 0 to 202
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country         202 non-null    object 
 1   ISO3            186 non-null    object 
 2   Region          186 non-null    object 
 3   CPI score 2021  180 non-null    float64
 4   Rank 2021       180 non-null    float64
 5   CPI score 2020  180 non-null    float64
 6   Rank 2020       180 non-null    float64
 7   CPI score 2019  180 non-null    float64
 8   Rank 2019       180 non-null    float64
 9   CPI score 2018  180 non-null    float64
 10  Rank 2018       180 non-null    float64
 11  CPI Score 2017  181 non-null    float64
 12  Rank 2017       180 non-null    float64
 13  CPI score 2016  176 non-null    float64
 14  Rank 2016       176 non-null    float64
 15  Region_2016     176 non-null    object 
 16  Rank 2015       168 non-null    float64
 17  CPI score 2015  168 non-null    flo

In [14]:
# while looking for the null country, we also discovered a country named GLOBAL AVARAGE below the previous row with index 186
# there's barely any data in the GLOBAL AVARAGE and we don't need any of them
# we decided to drop it
CPI.drop(187, axis=0, inplace=True)
CPI.iloc[[187]]

# dropping the columns didn't reset index; let's do that
CPI.reset_index(drop=True, inplace=True)

In [15]:
# there are some other peculiarities with the Country columns
# The USA has multiple rows representing it because their country names differ
# 1. United States of America
# 2. The United States of America
# 3. United States

CPI[CPI["Country"].str.match(r"(The )?United States")]

Country ISO3 Region  CPI score 2021  Rank 2021  \
27       United States of America  USA    AME            67.0       27.0   
186  The United States of America  NaN    NaN             NaN        NaN   
197                 United States  NaN    NaN             NaN        NaN   

     CPI score 2020  Rank 2020  CPI score 2019  Rank 2019  CPI score 2018  \
27             67.0       25.0            69.0       23.0            71.0   
186             NaN        NaN             NaN        NaN             NaN   
197             NaN        NaN             NaN        NaN             NaN   

     ...  Rank 2016  Region_2016  Rank 2015  CPI score 2015  Rank 2014  \
27   ...        NaN          NaN        NaN             NaN        NaN   
186  ...       18.0          AME        NaN             NaN        NaN   
197  ...        NaN          NaN       16.0            76.0       17.0   

    CPI score 2014  Rank 2013  CPI score 2013  Rank 2012  CPI score 2012  
27             NaN        NaN             NaN        NaN             NaN  
186            NaN        NaN             NaN        NaN             NaN  
197           74.0       19.0            73.0       19.0            73.0  

[3 rows x 24 columns]

In [16]:
# we'll stick with the row that has the most recent data ,i.e. row 27 with the name United States of America, 
# and fill the missing values using data from the older rows

CPI.loc[27, ["CPI score 2016", "Rank 2016"]] = CPI.loc[186, ["CPI score 2016", "Rank 2016"]]
CPI.loc[27, ["CPI score 2015", "Rank 2015", 
             "CPI score 2014", "Rank 2014", 
             "CPI score 2013", "Rank 2013", 
             "CPI score 2012", "Rank 2012"]] = CPI.loc[197, ["CPI score 2015", "Rank 2015", 
                                                             "CPI score 2014", "Rank 2014", 
                                                             "CPI score 2013", "Rank 2013", 
                                                             "CPI score 2012", "Rank 2012"]]


# we'll also drop the two rows and reset the index afterwards
CPI.drop([186, 197], axis=0, inplace=True)

CPI.iloc[[27]]


Country ISO3 Region  CPI score 2021  Rank 2021  \
27  United States of America  USA    AME            67.0       27.0   

    CPI score 2020  Rank 2020  CPI score 2019  Rank 2019  CPI score 2018  ...  \
27            67.0       25.0            69.0       23.0            71.0  ...   

    Rank 2016  Region_2016  Rank 2015  CPI score 2015  Rank 2014  \
27       18.0          NaN       16.0            76.0       17.0   

   CPI score 2014  Rank 2013  CPI score 2013  Rank 2012  CPI score 2012  
27           74.0       19.0            73.0       19.0            73.0  

[1 rows x 24 columns]

In [17]:
# Country has no null and duplicate values as of now
CPI.info()
CPI[CPI.duplicated(subset="Country")]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 0 to 200
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country         199 non-null    object 
 1   ISO3            186 non-null    object 
 2   Region          186 non-null    object 
 3   CPI score 2021  180 non-null    float64
 4   Rank 2021       180 non-null    float64
 5   CPI score 2020  180 non-null    float64
 6   Rank 2020       180 non-null    float64
 7   CPI score 2019  180 non-null    float64
 8   Rank 2019       180 non-null    float64
 9   CPI score 2018  180 non-null    float64
 10  Rank 2018       180 non-null    float64
 11  CPI Score 2017  180 non-null    float64
 12  Rank 2017       180 non-null    float64
 13  CPI score 2016  176 non-null    float64
 14  Rank 2016       176 non-null    float64
 15  Region_2016     175 non-null    object 
 16  Rank 2015       168 non-null    float64
 17  CPI score 2015  168 non-null    flo

Empty DataFrame
Columns: [Country, ISO3, Region, CPI score 2021, Rank 2021, CPI score 2020, Rank 2020, CPI score 2019, Rank 2019, CPI score 2018, Rank 2018, CPI Score 2017, Rank 2017, CPI score 2016, Rank 2016, Region_2016, Rank 2015, CPI score 2015, Rank 2014, CPI score 2014, Rank 2013, CPI score 2013, Rank 2012, CPI score 2012]
Index: []

[0 rows x 24 columns]

In [18]:
# ISO3 has a some null values as well
# we'll also be looking for duplicates once the null values are handled

CPI[CPI["ISO3"].isnull()]

Country ISO3 Region  CPI score 2021  Rank 2021  \
187  Saint Vincent and The Grenadines  NaN    NaN             NaN        NaN   
188                        Cape Verde  NaN    NaN             NaN        NaN   
189                            Brunei  NaN    NaN             NaN        NaN   
190                     Korea (South)  NaN    NaN             NaN        NaN   
191              The FYR of Macedonia  NaN    NaN             NaN        NaN   
192                     Côte d’Ivoire  NaN    NaN             NaN        NaN   
193  The Democratic Republic of Congo  NaN    NaN             NaN        NaN   
194                 Republic of Congo  NaN    NaN             NaN        NaN   
195                     Guinea-Bissau  NaN    NaN             NaN        NaN   
196                     Korea (North)  NaN    NaN             NaN        NaN   
198                     Côte d´Ivoire  NaN    NaN             NaN        NaN   
199                    Congo Republic  NaN    NaN             NaN        NaN   
200                       Puerto Rico  NaN    NaN             NaN        NaN   

     CPI score 2020  Rank 2020  CPI score 2019  Rank 2019  CPI score 2018  \
187             NaN        NaN             NaN        NaN             NaN   
188             NaN        NaN             NaN        NaN             NaN   
189             NaN        NaN             NaN        NaN             NaN   
190             NaN        NaN             NaN        NaN             NaN   
191             NaN        NaN             NaN        NaN             NaN   
192             NaN        NaN             NaN        NaN             NaN   
193             NaN        NaN             NaN        NaN             NaN   
194             NaN        NaN             NaN        NaN             NaN   
195             NaN        NaN             NaN        NaN             NaN   
196             NaN        NaN             NaN        NaN             NaN   
198             NaN        NaN             NaN        NaN             NaN   
199             NaN        NaN             NaN        NaN             NaN   
200             NaN        NaN             NaN        NaN             NaN   

     ...  Rank 2016  Region_2016  Rank 2015  CPI score 2015  Rank 2014  \
187  ...       35.0          AME        NaN             NaN        NaN   
188  ...       38.0          SSA       40.0            55.0       43.0   
189  ...       41.0           AP        NaN             NaN        NaN   
190  ...       52.0           AP       43.0            54.0       44.0   
191  ...       90.0          ECA       66.0            42.0       64.0   
192  ...      108.0          SSA        NaN             NaN        NaN   
193  ...      156.0          SSA        NaN             NaN        NaN   
194  ...      159.0          SSA        NaN             NaN        NaN   
195  ...      168.0          SSA      158.0            17.0      161.0   
196  ...      174.0           AP      167.0             8.0      174.0   
198  ...        NaN          NaN      106.0            32.0      115.0   
199  ...        NaN          NaN      146.0            23.0      152.0   
200  ...        NaN          NaN        NaN             NaN       31.0   

    CPI score 2014  Rank 2013  CPI score 2013  Rank 2012  CPI score 2012  
187            NaN        NaN             NaN        NaN             NaN  
188           57.0       41.0            58.0       39.0            60.0  
189            NaN       38.0            60.0       46.0            55.0  
190           55.0       46.0            55.0       45.0            56.0  
191           45.0        NaN             NaN        NaN             NaN  
192            NaN        NaN             NaN        NaN             NaN  
193            NaN        NaN             NaN        NaN             NaN  
194            NaN        NaN             NaN        NaN             NaN  
195           19.0      163.0            19.0      150.0            25.0  
196            8.0      175.0             8

In [19]:
# ignore this

# we decide to progressively lower the range until we can identify the problematic row's index
# we're doing it manually, but a function is more appropriate here

# this shows no nulls
# CPI[:100].info()

# this shows a null
# CPI[100:].info()

# this shows no nulls
# CPI[100:150].info()

# this shows a null
# CPI[150:].info()

# this shows no nulls
# CPI[150:175].info()

# this shows a null
# CPI[175:].info()

# explore the rows in the identified range
# CPI[175:]

# # index 186 is the problem. Why weren't we able to filter its Country?
# elusive_country = CPI.iloc[186]["Country"] 

# the value is "nan" but it's not a string

# type(elusive_country)



# and checking with math.isnan()
# type(CPI.iloc[186]["Country"])