# CPI Analysis

In [46]:
import numpy as np

arr = np.arange(9).reshape(3,3)

print(arr[:, :])
print(arr[:, [1,0,2]])



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [14]:
# import the necessary libraries and define utility functions
import pandas as pd


def overview(df):
    print(df.head(5))
    print(df.columns)
    print(df.describe())

In [103]:
# import CPI data from 2012-2021
CPI_2021 = pd.read_csv("datasets/CPI/CPI2021-Table 1.csv", header=2)
CPI_2020 = pd.read_csv("datasets/CPI/CPI2020-Table 1.csv", header=2)
CPI_2019 = pd.read_csv("datasets/CPI/CPI2019-Table 1.csv", header=2)
CPI_2018 = pd.read_csv("datasets/CPI/CPI2018-Table 1.csv", header=2)
CPI_2017 = pd.read_csv("datasets/CPI/CPI2017-Table 1.csv", header=2)
CPI_2016 = pd.read_csv("datasets/CPI/CPI2016-Table 1.csv")
CPI_2015 = pd.read_csv("datasets/CPI/CPI2015-Table 1.csv")
CPI_2014 = pd.read_csv("datasets/CPI/CPI2014-Table 1.csv")
CPI_2013 = pd.read_csv("datasets/CPI/CPI2013-Table 1.csv", header=1)
CPI_2012 = pd.read_csv("datasets/CPI/CPI2012-Table 1.csv")

cpi_years = list(reversed(range(2012,2022)))
cols_rename = { "Country / Territory": "Country"}

# 2021
# only retrieve the Country, ISO3, Region, CPI score, and rank columns
CPI_2021 = CPI_2021.iloc[:, :5]
CPI_2021.rename(columns={ "Country / Territory": "Country", "Rank": "Rank 2021"}, inplace=True)

# 2020
CPI_2020 = CPI_2020.iloc[:, :5]
CPI_2020.rename(columns={ "Rank": "Rank 2020"}, inplace=True)

CPI = CPI_2021.merge(CPI_2020, how="outer", on=["Country", "ISO3", "Region"])

# 2019
CPI_2019 = CPI_2019.iloc[:, :5]
CPI_2019.rename(columns={ "Rank": "Rank 2019"}, inplace=True)

CPI = CPI.merge(CPI_2019, how="outer", on=["Country", "ISO3", "Region"])

# 2018
CPI_2018 = CPI_2018.iloc[:, :5]
CPI_2018.rename(columns={ "Rank ": "Rank 2018"}, inplace=True)

CPI = CPI.merge(CPI_2018, how="outer", on=["Country", "ISO3", "Region"])


# 2017
CPI_2017 = CPI_2017.iloc[:, :5]
CPI_2017.rename(columns={ "Rank ": "Rank 2017"}, inplace=True)

CPI = CPI.merge(CPI_2017, how="outer", on=["Country", "ISO3", "Region"])

# 2016
CPI_2016 = CPI_2016.iloc[:, :4]
CPI_2016.rename(columns={ "CPI2016": "CPI score 2016", "Rank": "Rank 2016"}, inplace=True)

CPI = CPI.merge(CPI_2016, how="outer", on=["Country", "Region"])

# 2015
CPI_2015 = CPI_2015.iloc[:, :5]
CPI_2015 = CPI_2015.drop("Region", axis=1)
CPI_2015.rename(columns={ "CPI 2015 Score": "CPI score 2015", "Country Rank": "Rank 2015", "Country/Territory": "Country", "Country Code": "ISO3"}, inplace=True)

CPI = CPI.merge(CPI_2015, how="outer", on=["Country", "ISO3"])

# 2014
CPI_2014 = CPI_2014.iloc[:, :5]
CPI_2014.rename(columns={ "CPI 2014": "CPI score 2014", "Country Rank": "Rank 2014", "Country/Territory": "Country", "Country Code": "ISO3"}, inplace=True)

CPI = CPI.merge(CPI_2014, how="outer", on=["Country", "ISO3"], suffixes=["", "_2014"])
# sanity check
# CPI[CPI["Country"] == "Malaysia"]
# CPI_2017
CPI
# CPI_2014.columns

Country ISO3 Region  CPI score 2021  Rank 2021  CPI score 2020  \
0           Denmark  DNK  WE/EU            88.0        1.0            88.0   
1           Finland  FIN  WE/EU            88.0        1.0            85.0   
2       New Zealand  NZL     AP            88.0        1.0            88.0   
3            Norway  NOR  WE/EU            85.0        4.0            84.0   
4         Singapore  SGP     AP            85.0        4.0            85.0   
..              ...  ...    ...             ...        ...             ...   
207   Côte d´Ivoire  CIV    NaN             NaN        NaN             NaN   
208  Congo Republic  COG    NaN             NaN        NaN             NaN   
209   Guinea-Bissau  GNB    NaN             NaN        NaN             NaN   
210   Korea (North)  PRK    NaN             NaN        NaN             NaN   
211     Puerto Rico  PRI    NaN             NaN        NaN             NaN   

     Rank 2020  CPI score 2019  Rank 2019  CPI Score 2018  Rank 2018  \
0          1.0            87.0        1.0            88.0        1.0   
1          3.0            86.0        3.0            85.0        3.0   
2          1.0            87.0        1.0            87.0        2.0   
3          7.0            84.0        7.0            84.0        7.0   
4          3.0            85.0        4.0            85.0        3.0   
..         ...             ...        ...             ...        ...   
207        NaN             NaN        NaN             NaN        NaN   
208        NaN             NaN        NaN             NaN        NaN   
209        NaN             NaN        NaN             NaN        NaN   
210        NaN             NaN        NaN             NaN        NaN   
211        NaN             NaN        NaN             NaN        NaN   

     CPI Score 2017  Rank 2017  CPI score 2016  Rank 2016  Rank 2015  \
0              88.0        2.0            90.0        1.0        1.0   
1              85.0        3.0            89.0        3.0        3.0   
2              89.0        1.0            90.0        1.0        1.0   
3              85.0        3.0            85.0        6.0        5.0   
4              84.0        6.0            84.0        7.0        7.0   
..              ...        ...             ...        ...        ...   
207             NaN        NaN             NaN        NaN      106.0   
208             NaN        NaN             NaN        NaN      146.0   
209             NaN        NaN             NaN        NaN      158.0   
210             NaN        NaN             NaN        NaN      167.0   
211             NaN        NaN             NaN        NaN        NaN   

     CPI score 2015  Rank 2014 Region_2014  CPI score 2014  
0              91.0        1.0          EU            92.0  
1              90.0        3.0          EU            89.0  
2              91.0        2.0          AP            91.0  
3              88.0        5.0          EU            86.0  
4              85.0        7.0          AP            84.0  
..              ...        ...         ...             ...  
207            32.0      115.0          AF            32.0  
208            23.0      152.0          AF            23.0  
209            17.0      161.0          AF            19.0  
210             8.0      174.0          AP             8.0  
211             NaN       31.0          AM            63.0  

[212 rows x 20 columns]

In [39]:
CPI_2021.head(5)

Country / Territory ISO3 Region  CPI score 2021  Rank  Standard error  \
0             Denmark  DNK  WE/EU              88     1            1.85   
1             Finland  FIN  WE/EU              88     1            1.25   
2         New Zealand  NZL     AP              88     1            1.43   
3              Norway  NOR  WE/EU              85     4            1.07   
4           Singapore  SGP     AP              85     4            1.16   

   Number of sources  Lower CI  Upper CI  African Development Bank CPIA  ...  \
0                  8     84.96     91.04                            NaN  ...   
1                  8     85.95     90.05                            NaN  ...   
2                  8     85.65     90.35                            NaN  ...   
3                  7     83.24     86.76                            NaN  ...   
4                  9     83.09     86.91                            NaN  ...   

   Economist Intelligence Unit Country Ratings  \
0                                         90.0   
1                                         90.0   
2                                         90.0   
3                                         90.0   
4                                         90.0   

   Freedom House Nations in Transit  Global Insights Country Risk Ratings  \
0                               NaN                                    83   
1                               NaN                                    83   
2                               NaN                                    83   
3                               NaN                                    83   
4                               NaN                                    83   

   IMD World Competitiveness Yearbook  PERC Asia Risk Guide  \
0                                93.0                   NaN   
1                                94.0                   NaN   
2                                91.0                   NaN   
3                                81.0                   NaN   
4                                87.0                  91.0   

   PRS International Country Risk Guide  Varieties of Democracy Project  \
0                                 100.0                            79.0   
1                                  93.0                            77.0   
2                                  93.0                            78.0   
3                                  85.0                            78.0   
4                                  85.0                            78.0   

   World Bank CPIA  World Economic Forum EOS  \
0              NaN                      78.0   
1              NaN                      91.0   
2              NaN                      85.0   
3              NaN                       NaN   
4              NaN                      91.0   

   World Justice Project Rule of Law Index  
0                                     87.0  
1                                     87.0  
2                                     83.0  
3                                     87.0  
4                                     84.0  

[5 rows x 22 columns]

In [7]:
CPI_2021.columns

Index(['Country / Territory', 'ISO3', 'Region', 'CPI score 2021', 'Rank',
       'Standard error', 'Number of sources', 'Lower CI', 'Upper CI',
       'African Development Bank CPIA',
       'Bertelsmann Foundation Sustainable Governance Index',
       'Bertelsmann Foundation Transformation Index',
       'Economist Intelligence Unit Country Ratings',
       'Freedom House Nations in Transit',
       'Global Insights Country Risk Ratings',
       'IMD World Competitiveness Yearbook', 'PERC Asia Risk Guide',
       'PRS International Country Risk Guide',
       'Varieties of Democracy Project', 'World Bank CPIA',
       'World Economic Forum EOS', 'World Justice Project Rule of Law Index'],
      dtype='object')


In [5]:
CPI_2021.describe()

CPI score 2021        Rank  Standard error  Number of sources  \
count      180.000000  180.000000      180.000000         180.000000   
mean        43.266667   89.072222        2.152667           7.116667   
std         18.780591   51.881798        1.305921           1.819433   
min         11.000000    1.000000        0.410000           3.000000   
25%         29.750000   45.000000        1.320000           6.000000   
50%         39.000000   87.000000        1.710000           7.000000   
75%         55.000000  130.000000        2.555000           8.000000   
max         88.000000  180.000000        7.310000          10.000000   

         Lower CI    Upper CI  African Development Bank CPIA  \
count  180.000000  180.000000                      37.000000   
mean    39.725000   46.808333                      27.891892   
std     18.938347   18.867885                      12.013381   
min      9.890000   11.670000                       4.000000   
25%     26.262500   32.102500                      19.000000   
50%     35.270000   42.685000                      27.000000   
75%     51.465000   59.752500                      37.000000   
max     85.950000   91.040000                      49.000000   

       Bertelsmann Foundation Sustainable Governance Index  \
count                                          41.000000     
mean                                           64.341463     
std                                            18.385605     
min                                            26.000000     
25%                                            44.000000     
50%                                            70.000000     
75%                                            79.000000     
max                                            97.000000     

       Bertelsmann Foundation Transformation Index  \
count                                   137.000000   
mean                                     35.569343   
std                                      15.459528   
min                                       9.000000   
25%                                      25.000000   
50%                                      33.000000   
75%                                      41.000000   
max                                      77.000000   

       Economist Intelligence Unit Country Ratings  \
count                                   131.000000   
mean                                     45.816794   
std                                      22.063127   
min                                      20.000000   
25%                                      37.000000   
50%                                      37.000000   
75%                                      55.000000   
max                                      90.000000   

       Freedom House Nations in Transit  Global Insights Country Risk Ratings  \
count                         29.000000                            180.000000   
mean                          43.724138                             43.738889   
std                           15.417746                             18.597881   
min                           21.000000                             10.000000   
25%                           30.000000                             35.000000   
50%                           44.000000                             35.000000   
75%                           56.000000                             59.000000   
max                           71.000000                             83.000000   

       IMD World Competitiveness Yearbook  PERC Asia Risk Guide  \
count                           64.000000             15.000000   
mean                            56.234375             51.600000   
std                             21.016805             20.395378   
min                             20.000000             31.000000   
25%                             38.750000             37.000000   
50%                             53.500000             40.000000   
75%                             73.000000        